### ISSUE TITLE
假人无法链接至1.17.30 PowerNukkit服务器

### ISSUE THREAD

**Issue by Mcayear** [ddf8196/FakePlayer#34]
PowerNukkit服务器控制台报错，服务器未开启xbox-auth
```14:32:36 [INFO ] [/127.0.0.1:55444] 登出游戏，原因：Disconnected from Server
14:32:37 [ERROR] Unable to decode packet
java.lang.NullPointerException: null
        at cn.nukkit.network.protocol.LoginPacket.getAnimation(LoginPacket.java:159) ~[powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at cn.nukkit.network.protocol.LoginPacket.decodeSkinData(LoginPacket.java:122) ~[powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at cn.nukkit.network.protocol.LoginPacket.decode(LoginPacket.java:52) ~[powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at cn.nukkit.network.Network.processBatch(Network.java:267) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at cn.nukkit.network.RakNetInterface$NukkitRakNetSession.onEncapsulated(RakNetInterface.java:288) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:269) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:392) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:372) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:360) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:241) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:316) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]```

**Comment by ke-admin** [comment]
![Screenshot_2021-11-26-00-38-15-917_com android browser](https://user-images.githubusercontent.com/94810101/143477841-afc8685e-d93b-41e4-b438-e7ab082dc5e8.jpg)
![Screenshot_2021-11-26-00-24-10-270_com android browser](https://user-images.githubusercontent.com/94810101/143477868-8ca32cce-f420-4a17-b985-e93a260c56f0.jpg)
1.17.40假人无法进去

**Comment by NGT233** [comment]
我也是这样的问题

**Comment by Mcayear** [comment]
时隔多年，我重新浏览了这个问题。#95
原因是 LoginPacket 中 AnimatedImageData 属性增加了 AnimationExpression 值导致的。
