### ISSUE TITLE
客户端线程发生异常

### ISSUE THREAD

**Issue by updsky** [ddf8196/FakePlayer#73]
**Version & Environment 软件版本和环境**
 - BDS Version [e.g. 1.19.31.01]
 - FakePlayer Version [0.5.9]

**Describe the bug 你的问题的描述**
添加假人时报错：
客户端线程发生异常: java.lang.AssertionError: Unable to initialize required encryption
        at com.nukkitx.protocol.bedrock.util.EncryptionUtils.createCipher(EncryptionUtils.java:277)
        at com.nukkitx.protocol.bedrock.BedrockSession.enableEncryption(BedrockSession.java:236)
        at com.ddf.fakeplayer.network.ClientPacketHandler.handle(ClientPacketHandler.java:94)
        at com.nukkitx.protocol.bedrock.packet.ServerToClientHandshakePacket.handle(ServerToClientHandshakePacket.java:19)
        at com.ddf.fakeplayer.client.Client.update(Client.java:294)
        at com.ddf.fakeplayer.client.Client$ClientThread.run(Client.java:561)
Caused by: java.security.InvalidKeyException: Illegal key size
        at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
        at javax.crypto.Cipher.implInit(Cipher.java:805)
        at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
        at javax.crypto.Cipher.init(Cipher.java:1396)
        at javax.crypto.Cipher.init(Cipher.java:1327)
        at com.nukkitx.protocol.bedrock.util.EncryptionUtils.createCipher(EncryptionUtils.java:274)
        ... 5 more

**To Reproduce(Optional) 复现该问题的方法(可选)**
Steps to reproduce the behavior

**Screenshots or log 截图或日志**

![image](https://user-images.githubusercontent.com/50937659/194756521-c0fbd5ac-3d30-4117-8c89-8ceef417252b.png)

**Additional content 附加内容**
trusted-key已添加到服务器，并重启过服务了

**Comment by SkyAerope** [comment]
#55
